version: '3.8'
services:
  square-profit-app:
    container_name: square-profit-app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SQUARE_ENVIRONMENT=${SQUARE_ENVIRONMENT}
      - SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
