services:
  square-profit-app:
    container_name: square-profit-app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SQUARE_ENVIRONMENT=${SQUARE_ENVIRONMENT}
      - SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    volumes:
      - PF_GP_DASH:/app/data

volumes:
  PF_GP_DASH:
    driver: local